POST http://localhost:9090/register HTTP/1.1
Content-Type: application/json

{
 "username": "Chinky Rao",
  "password": "password1",
  "email": "Chinky@example.com",
  "name": "Chinky"
}

###

POST http://localhost:9090/login HTTP/1.1
Content-Type: application/json

{
    "email":"Chinky@example.com",
    "password":"password1"
}

###
POST http://localhost:9090/login HTTP/1.1
Content-Type: application/json 

{
    "email":"pro@example.com",
    "password":"password123"
}

###
GET http://localhost:9090/get_user_and_profile 
Content-Type: application/json

{
  "token":"3b4db84b6cf4f10c06b9e2660c66a20ad2cb9e9e4257e64ca918601a5d7912f9"
}

###
GET http://localhost:9090/get_user_and_profile
Content-Type: application/json

{
  "token":"b8bd6e0a10fb497fad11959f9d3e1d1bedfa67c5c4bc0696e0fd6fff32d08a2d"
}

###
POST http://localhost:9090/update_profile_data HTTP/1.1
Content-Type: application/json

{
  "token": "c9563e6c47b04ae554c3d927c234e9370f398535f218f6057ceac20ef2a1ac14",
  "bio": "Some bio text from rahul",
  "currentPost": [
  {
    "company": "Amazon",
    "position": "CTO",
    "years": "1"
  }
],
  "pastWork": [
    {
      "company": "Microsoft",
      "position": "CTO",
      "years": "2"
    }
  ],
  "education": [
    {
      "school": "IIT",
      "degree": "B.Tech",
      "fieldofStudy": "2015-2019"
    }
  ]
}

###

GET http://localhost:9090/users/get_all_users
